---
name: Build and Run-test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y build-essential cmake libssl-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arcadyan-decryptor
          path: ${{github.workspace}}/build

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: arcadyan-decryptor
          path: ${{github.workspace}}/build

      - name: Set executable permissions
        run: chmod +x ${{github.workspace}}/build/arcadyan_decryptor

      - name: Create output directory
        run: mkdir -p ${{github.workspace}}/build/output

      - name: Download image
        run: wget -O ${{github.workspace}}/build/output/image http://fw-acs.telekom.de/tftpboot/cpe/DT5GR2A/010149.1.0.007.4.signed

      - name: Install dependencies
        run: sudo apt-get install -y build-essential cmake libssl-dev

      - name: Run tests
        run: ${{github.workspace}}/build/arcadyan_decryptor ${{github.workspace}}/contrib/5gse.pem ${{github.workspace}}/build/output/image ${{github.workspace}}/output/build/

